### ISSUE TITLE
主链上线计划

### ISSUE THREAD

**Issue by fenoss01** [hybridnetwork/hxd#5]
.目前HSR 价格已经快到发型价，希望这周工作汇报里面能把主链上线的计划发出来，没有计划，我们持有人信仰啥的都快被磨完了。
1. 开发计划很重要
2. 社区赶紧找一些牛人和文案炒手
3. 搞一个站台的出来，跟我们粉丝互动
4. 多搞一点技术发布会

**Comment by bogrod** [comment]
This is for technical issues for hxd only. If you want to discuss the technology, please visit the hybrid.network community
