### ISSUE TITLE
vote ?

### ISSUE THREAD

**Issue by wittwitt** [hybridnetwork/hxd#7]
[ERR] WLLT: Failed to send vote for ticket hash 844c28ff7f9d22f84358c91c0f39500a1eb40ceb135cc233eebb7b5e2ae3631d: unmined transaction 9759d93318329c5d665d0f4f2ddc8b425f91712ed028d94f2fef2e852b66dc39 is a double spend of unmined transaction a2e6389e879e976d24354305933c98565feb9d2058f3e8212d2632019b7ea1c8

**Comment by bogrod** [comment]
This has been addressed in commit 90dcd25e18e888d33b152bad4c8d4233d9bdc36e in the wallet
